apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-bkc6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hihe-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-bkc6@sha256:e4a37a80f89f6b2a7ac8defdd934ea9a4154440b4e391a6f4abc9f74d369c506
        name: my-go
        resources: {}
status: {}
